In [1]:
#import necessary libraries
import nltk
import pandas as pd
import re
from textblob import TextBlob
import string

In [2]:
df=pd.read_csv("twitter_data.csv");
print(df['Tweets'])

0       b'RT @Heidi_LDN: Well said @presidentaejosh - ...
1       b'RT @naaathi_: HENDITHI ITS SAFE TO SAY I HAV...
2       b'RT @gauravm975: #Fight4Ews_Age_relaxation\n#...
3       b'RT @thedailybeast: A secret CDC report obtai...
4       b'RT @rlmcelreath: Cats reacting to bad COVID-...
                              ...
5494    b'RT @TajinderBagga: Urgent requirement of Pla...
5495    b"RT @MEFoggyDog: Masks.\n\nI've had 'suspecte...
5496    b'RT @NSWHealth: Three new cases of COVID-19 h...
5497    b'Testing for #coronavirus is available at Gov...
5498    b'RT @richardhine: BREAKING: #60Minutes invest...
Name: Tweets, Length: 5499, dtype: object

In [3]:
#TO remove all the noise data
def cleanTxt(text):
 text=text.lower() #Making tweets to lowerCase 
 text = re.sub('@[A-Za-z0–9]+', '', text) #Removing @mentions
 text = re.sub('#', '', text) # Removing '#' hash tag
 text = re.sub('b\'rt[\s]+', ' ', text) # Removing RT
 text = re.sub('https?:\/\/\S+', '', text) # Removing hyperlink
 text = re.sub('\[.*?\]','',text)
 text = re.sub('[%s]'%re.escape(string.punctuation),'',text)
 text = re.sub('\w*\d\w*','',text)
 bad_chars=['_','-',':','\\n']
 for i in bad_chars:
   text=text.replace(i,' ')
 
 return text

# Clean the tweets
df['Tweets'] = df['Tweets'].apply(cleanTxt)

# Show the cleaned tweets
df.head

<bound method NDFrame.head of                 Date                                             Tweets
0     7/6/2020 11:59   ldn well said   expecting families in london ...
1     7/6/2020 11:59    hendithi its safe to say i have recovered fr...
2     7/6/2020 11:59     nrespected sir post  our community will be ...
3     7/6/2020 11:59    a secret cdc report obtained by the new york...
4     7/6/2020 11:59    cats reacting to bad  models a short thread ...
...              ...                                                ...
5494  6/28/2020 7:30    urgent requirement of plasma donor for criti...
5495  6/28/2020 7:30  brt  masksnnive had suspected  still ill nearl...
5496  6/28/2020 7:30    three new cases of  have been diagnosed brin...
5497  6/28/2020 7:30  btesting for coronavirus is available at gover...
5498  6/28/2020 7:30    breaking  investigation reveals trump knowin...

[5499 rows x 2 columns]>

In [4]:
#function to remove stopwords
def clean_tweets(tweet):
 
    stop_words = set(stopwords.words('english'))
    word_tokens = word_tokenize(tweet)
    tweet = re.sub(r'‚Ä¶', '', tweet)
     
#filter using NLTK library append it to a string
    filtered_tweet = [w for w in word_tokens if not w in stop_words]
    filtered_tweet = []

#looping through conditions
    for w in word_tokens:
       
        if w not in stop_words and w not in string.punctuation:
            filtered_tweet.append(w)
    
    #print(filtered_tweet)
    return ' '.join(filtered_tweet)

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

df['Tweets'] = df['Tweets'].apply(clean_tweets)

df

                Date                                             Tweets
0     7/6/2020 11:59  ldn well said expecting families london pay pr...
1     7/6/2020 11:59                        hendithi safe say recovered
2     7/6/2020 11:59           nrespected sir post community vulnerable
3     7/6/2020 11:59  secret cdc report obtained new york times show...
4     7/6/2020 11:59  cats reacting bad models short thread beneath ...
...              ...                                                ...
5494  6/28/2020 7:30  urgent requirement plasma donor critical patie...
5495  6/28/2020 7:30  brt masksnnive suspected still ill nearly wks ...
5496  6/28/2020 7:30  three new cases diagnosed bringing total numbe...
5497  6/28/2020 7:30  btesting coronavirus available government run ...
5498  6/28/2020 7:30  breaking investigation reveals trump knowingly...

[5499 rows x 2 columns]

In [5]:
# Create a function to get the subjectivity
def getSubjectivity(text):
   return TextBlob(text).sentiment.subjectivity

# Create a function to get the polarity
def getPolarity(text):
   return  TextBlob(text).sentiment.polarity


# Create two new columns 'Subjectivity' & 'Polarity'
df['Subjectivity'] = df['Tweets'].apply(getSubjectivity)
df['Polarity'] = df['Tweets'].apply(getPolarity)

# Show the new dataframe with columns 'Subjectivity' & 'Polarity'
df

,Date,Tweets,Subjectivity,Polarity
0,7/6/2020 11:59,ldn well said expecting families london pay pr...,0.375000,-0.125000
1,7/6/2020 11:59,hendithi safe say recovered,0.500000,0.500000
2,7/6/2020 11:59,nrespected sir post community vulnerable,0.500000,-0.500000
3,7/6/2020 11:59,secret cdc report obtained new york times show...,0.646970,-0.107576
4,7/6/2020 11:59,cats reacting bad models short thread beneath ...,0.425595,-0.053571
...,...,...,...,...
5494,6/28/2020 7:30,urgent requirement plasma donor critical patie...,0.733333,0.166667
5495,6/28/2020 7:30,brt masksnnive suspected still ill nearly wks ...,0.700000,-0.200000
5496,6/28/2020 7:30,three new cases diagnosed bringing total numbe...,0.602273,0.068182
5497,6/28/2020 7:30,btesting coronavirus available government run ...,0.166667,0.133333
5498,6/28/2020 7:30,breaking investigation reveals trump knowingly...,0.500000,-0.500000

In [6]:
def getAnalysis(score):
  if score < 0:
    return 'Negative'
  elif score == 0:
    return 'Neutral'
  else:
    return 'Positive'
df['Analysis'] = df['Polarity'].apply(getAnalysis)
# Show the dataframe
df

,Date,Tweets,Subjectivity,Polarity,Analysis
0,7/6/2020 11:59,ldn well said expecting families london pay pr...,0.375000,-0.125000,Negative
1,7/6/2020 11:59,hendithi safe say recovered,0.500000,0.500000,Positive
2,7/6/2020 11:59,nrespected sir post community vulnerable,0.500000,-0.500000,Negative
3,7/6/2020 11:59,secret cdc report obtained new york times show...,0.646970,-0.107576,Negative
4,7/6/2020 11:59,cats reacting bad models short thread beneath ...,0.425595,-0.053571,Negative
...,...,...,...,...,...
5494,6/28/2020 7:30,urgent requirement plasma donor critical patie...,0.733333,0.166667,Positive
5495,6/28/2020 7:30,brt masksnnive suspected still ill nearly wks ...,0.700000,-0.200000,Negative
5496,6/28/2020 7:30,three new cases diagnosed bringing total numbe...,0.602273,0.068182,Positive
5497,6/28/2020 7:30,btesting coronavirus available government run ...,0.166667,0.133333,Positive
5498,6/28/2020 7:30,breaking investigation reveals trump knowingly...,0.500000,-0.500000,Negative

In [7]:
import plotly.graph_objects as go
import dash
import dash_html_components as html
import pandas as pd
import dash_core_components as dcc

In [8]:
import plotly.graph_objects as go
from plotly.offline import init_notebook_mode

#initialising the values for plotting
labels = ["Positive","Negative","Neutral"]
values = df['Analysis'].value_counts().values

trace = go.Pie(labels=labels,values=values)
layout = go.Layout(
        title="Sentiment Analysis Representation",
        height=600,
        margin=go.layout.Margin(l=50, r=50, b=100, t=50, pad=6)   
        )

In [9]:
#modifying list data for display purpose
disp_labels=[]
disp_values=[]
for i in list(labels):
    disp_labels.append(i + ' ')
for i in list(values):
    disp_values.append(str(i) + ' ')

In [ ]:
#displaying the content on server
app=dash.Dash()
app.layout = html.Div(children=[
    html.H1(children='Twitter Sentiment Analysis',
            style={
                    'text-align':'center',
                    'color':'white',
                    'background-color': 'coral',
                    'height':'60px'
            }),
            
    html.Div(children="DashBoard",
            style={
                    'text-align':'center',
                    'color':'white',
                    'background-color': 'black',
                    'display':'inline-block',
                    'width':'30%' ,
                    'height':'550px',
                    'font-size':'25px',
                    'position':'absolute',
                    'top': '13%',
            }),
            html.H2(children=disp_labels,
            style={
                    'text-align':'left',
                    'color':'white',
                    'position':'absolute',
                    'top': '20%',
                    'left':'5%',
                    'word-spacing': '20px'
                }),
            html.H2(children=disp_values,
            style={
                    'text-align':'left',
                    'color':'white',
                    'position':'absolute',
                    'top': '25%',
                    'left':'7%',
                    'word-spacing': '50px'                    
                }),
                html.Div(children=[dcc.Graph(
                            id='example-graph',
                        figure={
                            'data': [trace],
                            'layout':layout
                        },style={
                    'background-color': 'cyan',
                    'width':'600px',
                    'position':'absolute',
                    'top': '20%',
                    'left':'42%'
                    
             })],
             ),
    
])

 

#Run the model on server
if __name__ == '__main__':
    app.run_server()

Dash is running on http://127.0.0.1:8050/

 Warning: This is a development server. Do not use app.run_server
 in production, use a production WSGI server like gunicorn instead.

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [15/Jul/2020 18:03:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Jul/2020 18:03:57] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [15/Jul/2020 18:03:57] "GET /_dash-layout HTTP/1.1" 200 -